/** Narasi HMI Evidence berfokus pada tata kelola perkaderan berbasis bukti. */
export const evidenceStory = [
  {
    label: "Organisasi bergerak",
    era: "Dari forum ke forum",
    chapter: "Struktur terus berjalan",
    title: "Organisasi terus bergerak. Apakah perjalanan kader ikut terbaca?",
    body: "Setiap periode menghadirkan kepengurusan, Rapat Anggota Komisariat, Konferensi Cabang, Musyawarah Daerah, Kongres, dan Rapat Kerja. Rapat Bidang, Rapat Presidium, Rapat Harian, serta Pleno memastikan roda organisasi tetap berjalan.",
    bridge: "Namun, keberlangsungan struktur belum selalu berarti organisasi memahami perjalanan kadernya.",
    image: "04-lingkaran-organisasi",
    position: "53% 50%",
    symbol: "↻",
  },
  {
    label: "Perjalanan kader",
    era: "Selepas Latihan Kader",
    chapter: "Nama tercatat, pengalaman terputus",
    title: "Nama kader tercatat. Perjalanannya belum tentu terbaca.",
    body: "HMI dapat mengetahui siapa yang telah mengikuti Latihan Kader. Tetapi organisasi belum tentu mengetahui siapa yang tetap aktif, siapa yang berhenti, kompetensi apa yang berkembang, mengapa prosesnya terputus, dan dukungan apa yang mereka perlukan.",
    bridge: "Jumlah peserta memberi angka. Perjalanan kader memberi makna yang dibutuhkan untuk membina.",
    image: "02-kelahiran-hmi",
    position: "58% 50%",
    symbol: "Kader",
  },
  {
    label: "Data dan pengetahuan",
    era: "Komisariat sampai PB",
    chapter: "Notulensi/dokumentasi belum terhubung",
    title: "Data ada di banyak tempat, tetapi tidak pernah digunakan seutuhnya.",
    body: "Komisariat, Cabang, Badko, dan Pengurus Besar dapat memiliki notulensi/dokumentasi serta definisi yang berbeda tentang anggota, alumni latihan, aktivitas, kompetensi, dan perkembangan kader. Data dihasilkan di banyak tempat, tetapi tidak digunakan seutuhnya sehingga tidak menjadi insight untuk organisasi.",
    bridge: "Definisi, data, dan insight perlu dikelola agar transisi kepemimpinan dapat berkelanjutan.",
    image: "01-indonesia",
    position: "52% 50%",
    symbol: "Data",
  },
  {
    label: "Ruang keputusan",
    era: "Rapat Bidang sampai Pleno",
    chapter: "Ketika asumsi menjadi dasar",
    title: "Program disusun. Student Needs dan Student Interest belum selalu hadir.",
    body: "Ketika perjalanan kader tidak terbaca, Rapat Bidang menyusun kegiatan, Rapat Presidium menentukan langkah, Rapat Harian menelaah pelaksanaan, dan Pleno mengevaluasi organisasi dengan pengetahuan yang tidak utuh. Program akhirnya sedikit demi sedikit memiliki jalan yang berbeda antara visi kepengurusan dan misi organisasi.",
    bridge: "HMI pun berisiko menawarkan jawaban lama kepada mahasiswa yang menghadapi persoalan baru.",
    image: "03-perubahan-zaman",
    position: "65% 50%",
    symbol: "?",
  },
  {
    label: "Energi organisasi",
    era: "Di tengah dinamika internal",
    chapter: "Yang lebih mudah dipetakan",
    title: "Peta dukungan terlihat lebih jelas daripada perjalanan kader.",
    body: "Menjelang Rapat Anggota Komisariat, Konferensi Cabang, Musyawarah Daerah, atau Kongres, dukungan dan delegasi dapat dipetakan dengan cermat. Namun, organisasi belum tentu mengetahui komisariat mana yang kehilangan kader setelah latihan atau cabang mana yang membutuhkan penguatan pembinaan.",
    bridge: "Ketika energi lebih banyak terserap ke dalam, jarak dengan persoalan mahasiswa dan masyarakat semakin melebar.",
    image: "04-lingkaran-organisasi",
    position: "53% 50%",
    symbol: "HMI",
  },
  {
    label: "Ekosistem berbasis bukti",
    era: "HMI Evidence",
    chapter: "Pengalaman menjadi dasar keputusan",
    title: "Menghadirkan Pengalaman Kader ke Dalam Keputusan Organisasi.",
    body: "Melalui ekosistem perkaderan berbasis bukti atau evidence-based, Komisariat mengenali perjalanan kader dan tindak lanjutnya. Cabang membaca pola antarkomisariat. Badko menghubungkan pengalaman antarcabang. Pengurus Besar mengolah pola nasional menjadi arah kebijakan, pedoman, dan dukungan perkaderan.",
    bridge: "Bukti bukan alat untuk membuat peringkat, melainkan cara menemukan titik yang perlu didukung, dipelajari, dan diperbaiki.",
    image: "05-berbasis-bukti",
    position: "62% 50%",
    symbol: "Bukti",
  },
] as const;

export const storyImage = (name: string) => `/scrollytelling/hmi-evidence-${name}-v1.webp`;
