export type KelompokId = "kaderisasi" | "tata-kelola" | "pengetahuan" | "target-program" | "evaluasi-arsip" | "data-jaringan";

export interface KelompokIndikator {
  id: KelompokId;
  judul: string;
  sorotan: string;
  namaDiBuku: string;
  arahPerbaikan: string;
}

export interface Indikator {
  nomor: number;
  teks: string;
  kelompok: KelompokId;
  pertanyaan: string;
  praktik: string;
  program?: string[];
}

export const sumberIndikator = {
  penulis: "Agussalim Sitompul",
  judul: "44 Indikator Kemunduran HMI: Suatu Kritikan dan Koreksi untuk Kebangkitan Kembali HMI",
  penerbit: "CV Misaka Galiza",
  kota: "Jakarta",
  tahun: 2006,
} as const;

/** Enam kelompok persoalan, memakai nama yang sama dengan persoalanHmi di evidence-story.ts. */
export const kelompokIndikator: readonly KelompokIndikator[] = [
  {
    id: "kaderisasi",
    judul: "Kaderisasi",
    sorotan: "Perjalanan kader",
    namaDiBuku: "Relevansi perkaderan",
    arahPerbaikan: "Menyesuaikan proses belajar, pendampingan, dan karya dengan kebutuhan mahasiswa yang benar-benar ditemukan. Perkaderan terhubung dengan pendampingan yang berkelanjutan dan karya yang menunjukkan pertumbuhan kader.",
  },
  {
    id: "tata-kelola",
    judul: "Tata Kelola",
    sorotan: "Akuntabilitas",
    namaDiBuku: "Kewenangan dan kritik",
    arahPerbaikan: "Memperjelas mandat dan pertanggungjawaban, menyimpan alasan keputusan, serta mengelola konflik kepentingan. Kritik yang jujur dan beralasan dilindungi agar tidak menjadi alat saling menjatuhkan.",
  },
  {
    id: "pengetahuan",
    judul: "Pengetahuan",
    sorotan: "Tradisi intelektual",
    namaDiBuku: "Teknologi dan riset",
    arahPerbaikan: "Memperkuat riset, sintesis bukti, pengelolaan pengetahuan, dan penggunaan teknologi yang bertanggung jawab, sehingga kerja pengetahuan menjadi pekerjaan organisasi yang terus hidup.",
  },
  {
    id: "target-program",
    judul: "Target Program",
    sorotan: "Keterukuran",
    namaDiBuku: "Diagnosis dan bukti",
    arahPerbaikan: "Membiasakan diri menyatakan masalah, keadaan awal, dan hasil yang ingin dicapai sebelum memilih kegiatan, sehingga alasan pilihan dan ukuran hasilnya dapat diperiksa.",
  },
  {
    id: "evaluasi-arsip",
    judul: "Evaluasi dan Arsip",
    sorotan: "Pembelajaran",
    namaDiBuku: "Evaluasi dan memory",
    arahPerbaikan: "Menghubungkan evaluasi dengan keputusan berikutnya dan menjaga pengetahuan lintas periode, agar keberhasilan, kegagalan, dan hubungan yang telah dibangun tidak hilang bersama pergantian pengurus.",
  },
  {
    id: "data-jaringan",
    judul: "Data dan Jaringan",
    sorotan: "Informasi",
    namaDiBuku: "Data dan informasi",
    arahPerbaikan: "Menyederhanakan data yang dikumpulkan dan memastikan setiap data punya tujuan, mutu, pengguna, dan batas akses yang jelas. Informasi harus kembali bermanfaat bagi pihak yang mengumpulkannya.",
  },
];

/** 44 indikator kemunduran HMI yang dihimpun Agussalim Sitompul (2006), dengan urutan asli. */
export const indikator: readonly Indikator[] = [
  {
    nomor: 1,
    teks: "Jumlah mahasiswa baru yang masuk HMI menurun.",
    kelompok: "kaderisasi",
    pertanyaan: "Berapa mahasiswa baru yang ikut LK 1 lewat komisariat kita dalam tiga tahun terakhir, dan apa yang membuat angkanya berubah?",
    praktik: "Kumpulkan daftar peserta LK 1 tiga tahun terakhir dalam satu tabel sederhana. Tanyakan kepada lima kader baru apa yang membuat mereka memutuskan bergabung.",
    program: ["06", "03"],
  },
  {
    nomor: 2,
    teks: "Jarak HMI dengan kehidupan mahasiswa semakin lebar.",
    kelompok: "kaderisasi",
    pertanyaan: "Apa tiga persoalan yang paling sering dikeluhkan mahasiswa di kampus kita, dan adakah kegiatan kita yang menjawabnya?",
    praktik: "Sebarkan survei singkat lima pertanyaan tentang Student Needs dan Student Interest kepada mahasiswa di kampus. Bahas hasilnya dalam rapat pengurus sebelum menyusun kegiatan bulan depan.",
    program: ["06"],
  },
  {
    nomor: 3,
    teks: "Pola perkaderan tertinggal dari tuntutan abad ke-21.",
    kelompok: "kaderisasi",
    pertanyaan: "Kapan terakhir kali materi dan metode latihan kader di tempat kita ditinjau ulang, dan atas dasar apa?",
    praktik: "Minta peserta LK 1 terakhir menilai setiap materi: mana yang berguna dan mana yang perlu diperbarui. Serahkan rangkumannya kepada pengelola latihan sebagai bahan perbaikan.",
    program: ["01", "08"],
  },
  {
    nomor: 4,
    teks: "Kader penerus kurang melanjutkan pandangan visioner para pendahulu.",
    kelompok: "kaderisasi",
    pertanyaan: "Apakah kader kita mengenal gagasan para pendahulu dari membaca karyanya langsung, atau hanya dari cerita dan kutipan?",
    praktik: "Pilih satu tulisan tokoh pendahulu HMI dan baca bersama dalam satu sesi diskusi. Minta peserta menulis satu paragraf tentang relevansinya bagi kampus hari ini.",
    program: ["09"],
  },
  {
    nomor: 5,
    teks: "Sebagian aparat organisasi, seperti Badko, kurang berfungsi.",
    kelompok: "tata-kelola",
    pertanyaan: "Dukungan apa yang seharusnya kita terima dari jenjang di atas kita menurut konstitusi, dan mana yang benar-benar berjalan?",
    praktik: "Tuliskan tugas dan kewenangan setiap jenjang menurut konstitusi dalam satu halaman. Tandai mana yang berjalan dan mana yang tersendat, lalu sampaikan catatannya melalui forum resmi.",
    program: ["11"],
  },
  {
    nomor: 6,
    teks: "Komisariat belum optimal dalam rekrutmen dan pembinaan anggota.",
    kelompok: "kaderisasi",
    pertanyaan: "Siapa yang bertanggung jawab atas pembinaan setiap angkatan baru di komisariat kita, dan apakah namanya tercatat?",
    praktik: "Tetapkan satu penanggung jawab pembinaan untuk angkatan LK 1 terakhir. Minta ia menyusun jadwal pertemuan sebulan ke depan dan mencatat siapa saja yang hadir.",
    program: ["01", "02"],
  },
  {
    nomor: 7,
    teks: "Komisariat belum tumbuh di seluruh perguruan tinggi dalam satu kota.",
    kelompok: "kaderisasi",
    pertanyaan: "Di kampus mana saja di kota kita ada mahasiswa yang tertarik pada HMI, tetapi belum ada komisariatnya?",
    praktik: "Petakan perguruan tinggi di wilayah cabang beserta ada atau tidaknya komisariat. Tanyakan kepada kader yang punya kenalan di kampus tanpa komisariat apa kebutuhan mahasiswa di sana.",
    program: ["06"],
  },
  {
    nomor: 8,
    teks: "Manajemen organisasi lemah dan tertinggal dari kebutuhan kontemporer.",
    kelompok: "tata-kelola",
    pertanyaan: "Apakah pembagian tugas, jadwal, dan keuangan kepengurusan kita tercatat di satu tempat yang bisa dibuka semua pengurus?",
    praktik: "Buat satu dokumen bersama berisi pembagian tugas, tenggat, dan penanggung jawab setiap program. Tinjau dokumen itu di setiap rapat harian selama sebulan.",
    program: ["10", "11"],
  },
  {
    nomor: 9,
    teks: "Pemahaman, penghayatan, dan pengamalan ajaran Islam masih kurang.",
    kelompok: "kaderisasi",
    pertanyaan: "Apakah kajian keislaman di komisariat kita berangkat dari pertanyaan nyata yang dihadapi kader sehari-hari?",
    praktik: "Kumpulkan secara anonim pertanyaan keislaman yang paling sering muncul di kalangan kader. Jadikan tiga pertanyaan teratas sebagai tema kajian rutin bulan ini.",
    program: ["01", "06"],
  },
  {
    nomor: 10,
    teks: "Pengetahuan mengenai ke-HMI-an dan organisasi belum optimal.",
    kelompok: "kaderisasi",
    pertanyaan: "Setelah LK 1, di mana kader kita belajar lebih lanjut tentang konstitusi, sejarah, dan cara kerja HMI?",
    praktik: "Susun agenda belajar lanjutan singkat untuk kader baru, misalnya membaca konstitusi bersama dan mengenal struktur organisasi. Jalankan satu sesi bulan ini dan catat pertanyaan yang muncul.",
    program: ["01"],
  },
  {
    nomor: 11,
    teks: "Lembaga kekaryaan HMI kurang berfungsi.",
    kelompok: "tata-kelola",
    pertanyaan: "Apakah lembaga kekaryaan di cabang kita punya program, penanggung jawab, dan laporan kegiatan yang jelas?",
    praktik: "Undang pengurus lembaga kekaryaan ke rapat cabang untuk menyampaikan program dan kendalanya. Catat kesepakatan dukungan yang diberikan dan kapan akan ditinjau kembali.",
    program: ["09", "11"],
  },
  {
    nomor: 12,
    teks: "Dies Natalis tidak lagi semarak dengan kegiatan ilmiah, sosial, seni, dan karya.",
    kelompok: "kaderisasi",
    pertanyaan: "Pada Dies Natalis terakhir, karya apa yang dihasilkan kader kita selain acara seremonial?",
    praktik: "Rancang peringatan berikutnya sebagai ajang pameran karya kader: tulisan, riset kecil, kegiatan sosial, atau karya seni. Buka pendaftaran karyanya mulai bulan ini.",
    program: ["09"],
  },
  {
    nomor: 13,
    teks: "Kegiatan HMI sepi dari pengunjung.",
    kelompok: "kaderisasi",
    pertanyaan: "Pada kegiatan terakhir kita, siapa yang datang, siapa yang tidak, dan pernahkah kita menanyakan alasannya?",
    praktik: "Setelah kegiatan berikutnya, minta peserta mengisi umpan balik tiga pertanyaan. Tanyakan juga kepada beberapa kader yang tidak hadir apa yang membuat mereka berhalangan atau kurang tertarik.",
    program: ["06", "03"],
  },
  {
    nomor: 14,
    teks: "Tradisi intelektual HMI memudar.",
    kelompok: "pengetahuan",
    pertanyaan: "Dalam sebulan terakhir, berapa tulisan, kajian, atau diskusi berbasis bacaan yang lahir dari komisariat kita?",
    praktik: "Mulai lingkar baca dua mingguan dengan satu bacaan yang disepakati. Minta satu peserta menulis ringkasan dan tanggapannya untuk diterbitkan di kanal komisariat.",
    program: ["09"],
  },
  {
    nomor: 15,
    teks: "Gagasan dan karya HMI belum cukup menjawab persoalan masyarakat.",
    kelompok: "pengetahuan",
    pertanyaan: "Persoalan masyarakat apa di sekitar kampus kita yang bisa dikaji atau dibantu kader, dan siapa yang sedang mengerjakannya?",
    praktik: "Pilih satu persoalan warga di sekitar kampus dan bentuk tim kecil untuk mengumpulkan data sederhana. Tuliskan temuan dan usulan solusinya dalam satu tulisan pendek.",
    program: ["09"],
  },
  {
    nomor: 16,
    teks: "Basis intelektual di kampus-kampus unggulan melemah.",
    kelompok: "pengetahuan",
    pertanyaan: "Apakah kita tahu bidang keahlian yang sedang ditekuni kader kita, dan bagaimana organisasi mendukungnya?",
    praktik: "Buat daftar sederhana bidang studi dan minat riset kader. Pertemukan kader dengan minat serupa dalam satu diskusi atau kelompok kajian.",
    program: ["05", "09"],
  },
  {
    nomor: 17,
    teks: "Tindak lanjut perkaderan tidak berjalan sebagaimana mestinya.",
    kelompok: "kaderisasi",
    pertanyaan: "Tiga bulan setelah LK 1 terakhir, berapa peserta yang masih aktif, dan apakah kita tahu alasan yang lain berhenti?",
    praktik: "Hubungi seluruh peserta LK 1 terakhir satu per satu. Catat siapa yang masih aktif, siapa yang berhenti, dan alasannya, lalu bahas temuan itu di rapat pengurus.",
    program: ["01", "02", "03"],
  },
  {
    nomor: 18,
    teks: "Evaluasi perjalanan organisasi dan program kerja jarang dilakukan secara terencana dan berkelanjutan.",
    kelompok: "evaluasi-arsip",
    pertanyaan: "Apakah setiap program kita ditutup dengan evaluasi tertulis, dan apakah catatan itu dibaca sebelum menyusun program berikutnya?",
    praktik: "Setelah kegiatan berikutnya, luangkan tiga puluh menit untuk evaluasi dengan tiga pertanyaan: apa yang berjalan, apa yang tidak, dan apa yang akan diubah. Simpan hasilnya di folder bersama.",
    program: ["10"],
  },
  {
    nomor: 19,
    teks: "Kegiatan keislaman mahasiswa di dalam dan luar kampus berkembang di luar HMI.",
    kelompok: "kaderisasi",
    pertanyaan: "Kegiatan keislaman apa yang ramai diikuti mahasiswa di kampus kita, dan apa yang bisa kita pelajari darinya?",
    praktik: "Pelajari dua kegiatan keislaman yang ramai diminati mahasiswa di kampus. Catat apa yang membuat mahasiswa tertarik, lalu diskusikan apa yang relevan untuk kajian komisariat.",
    program: ["06"],
  },
  {
    nomor: 20,
    teks: "Peran HMI dalam gerakan mahasiswa regional dan nasional menurun.",
    kelompok: "tata-kelola",
    pertanyaan: "Ketika kita menyatakan sikap atas suatu isu, apakah sikap itu didasari kajian dan diputuskan melalui mekanisme yang jelas?",
    praktik: "Sebelum menyatakan sikap berikutnya, siapkan ringkasan kajian satu halaman: duduk persoalan, data, pilihan sikap, dan alasannya. Simpan ringkasan itu bersama catatan keputusan.",
    program: ["05", "10"],
  },
  {
    nomor: 21,
    teks: "Organisasi mahasiswa Islam baru bermunculan.",
    kelompok: "kaderisasi",
    pertanyaan: "Apa yang membuat mahasiswa baru memilih organisasi lain, dan apa yang khas dari pengalaman ber-HMI di kampus kita?",
    praktik: "Tanyakan kepada beberapa mahasiswa baru organisasi apa saja yang mereka pertimbangkan dan alasannya. Rumuskan bersama pengurus apa yang khas dari perkaderan di komisariat kita.",
    program: ["06"],
  },
  {
    nomor: 22,
    teks: "Persoalan internal antara HMI DIPO dan HMI MPO berlarut-larut.",
    kelompok: "tata-kelola",
    pertanyaan: "Dari mana kader kita mengenal sejarah perbedaan jalan HMI DIPO dan HMI MPO: dari catatan yang utuh atau dari cerita sepihak?",
    praktik: "Adakan satu diskusi sejarah dengan bahan bacaan dari berbagai sudut pandang, dipandu kader yang menguasai sumbernya. Tekankan tradisi kader yang sama dan catat pertanyaan yang masih terbuka.",
  },
  {
    nomor: 23,
    teks: "HMI kehilangan figur panutan.",
    kelompok: "tata-kelola",
    pertanyaan: "Siapa kader atau alumni yang karya dan pengabdiannya layak diteladani, dan sudahkah kita mengenalkannya kepada kader baru?",
    praktik: "Undang satu alumni atau kader senior untuk berbagi perjalanan karya dan pengabdiannya, termasuk kegagalannya. Tuliskan ringkasannya agar bisa dibaca angkatan berikutnya.",
    program: ["02", "10"],
  },
  {
    nomor: 24,
    teks: "Program mudah dibuat, tetapi agenda pelaksanaannya lemah.",
    kelompok: "target-program",
    pertanyaan: "Dari semua program yang disahkan di awal periode, berapa yang sudah punya jadwal, penanggung jawab, dan anggaran?",
    praktik: "Ambil daftar program hasil rapat kerja. Lengkapi setiap program dengan tanggal pelaksanaan, penanggung jawab, dan langkah pertama, lalu tinjau kemajuannya setiap dua minggu.",
    program: ["10"],
  },
  {
    nomor: 25,
    teks: "Program disusun tanpa target yang jelas.",
    kelompok: "target-program",
    pertanyaan: "Untuk program terbesar kita periode ini, perubahan apa yang ingin dicapai, dan bagaimana kita tahu bahwa itu tercapai?",
    praktik: "Tuliskan untuk setiap program: masalah yang dijawab, keadaan awal, dan satu ukuran hasil. Contohnya, jumlah peserta LK 1 yang masih aktif tiga bulan setelah latihan.",
    program: ["03", "05"],
  },
  {
    nomor: 26,
    teks: "Strategi perjuangan HMI melemah.",
    kelompok: "tata-kelola",
    pertanyaan: "Apakah arah kerja kepengurusan kita tertulis jelas, dan apakah setiap program bisa ditelusuri kembali ke arah itu?",
    praktik: "Tuliskan arah kerja kepengurusan dalam satu halaman dan sandingkan dengan daftar program. Tandai program yang hubungannya dengan arah itu tidak jelas untuk dibahas ulang.",
    program: ["05"],
  },
  {
    nomor: 27,
    teks: "Retorika lebih banyak daripada tindakan.",
    kelompok: "target-program",
    pertanyaan: "Dari rencana dan pernyataan yang kita sampaikan bulan lalu, mana yang sudah dikerjakan, dan siapa yang mengerjakannya?",
    praktik: "Tutup setiap rapat dengan daftar tindak lanjut: apa yang dikerjakan, oleh siapa, dan kapan. Buka rapat berikutnya dengan memeriksa daftar itu sebelum membahas hal baru.",
    program: ["10"],
  },
  {
    nomor: 28,
    teks: "Kader pemecah masalah kurang berkembang dibandingkan kader penggalang solidaritas.",
    kelompok: "kaderisasi",
    pertanyaan: "Apakah kader yang tekun memecahkan masalah mendapat ruang dan penghargaan yang sama dengan kader yang pandai menggalang massa?",
    praktik: "Beri satu kelompok kader tugas memecahkan satu masalah nyata komisariat, misalnya merapikan data anggota. Dampingi prosesnya dan apresiasi hasilnya di forum komisariat.",
    program: ["08", "09"],
  },
  {
    nomor: 29,
    teks: "Keterlibatan dalam politik menyerap perhatian, tenaga, pikiran, dan dana.",
    kelompok: "tata-kelola",
    pertanyaan: "Dalam setahun terakhir, berapa bagian waktu, tenaga, dan dana kita yang terserap urusan politik dibanding perkaderan?",
    praktik: "Tinjau agenda dan pengeluaran tiga bulan terakhir, lalu kelompokkan ke perkaderan, karya, dan urusan lain. Bahas hasilnya secara terbuka di rapat pengurus sebagai bahan menata prioritas.",
    program: ["11"],
  },
  {
    nomor: 30,
    teks: "Gagasan pembaruan HMI tidak lagi tampak kuat.",
    kelompok: "pengetahuan",
    pertanyaan: "Kapan terakhir kali komisariat kita melahirkan gagasan baru yang ditulis, didiskusikan, dan diuji?",
    praktik: "Buka forum gagasan bulanan: setiap kader boleh mengajukan satu usulan perbaikan organisasi secara tertulis. Pilih satu usulan untuk diuji coba dalam skala kecil.",
    program: ["09"],
  },
  {
    nomor: 31,
    teks: "Pertumbuhan massa tidak diimbangi perkaderan yang intensif dan selektif.",
    kelompok: "kaderisasi",
    pertanyaan: "Apakah jumlah pendamping di komisariat kita sebanding dengan jumlah kader baru yang perlu dibina?",
    praktik: "Hitung perbandingan pendamping dan kader baru di komisariat. Jika satu pendamping membina terlalu banyak kader, bagi ulang kelompoknya atau libatkan kader senior dan alumni sebagai pendamping.",
    program: ["02"],
  },
  {
    nomor: 32,
    teks: "Daya kritis aktivis HMI menurun.",
    kelompok: "tata-kelola",
    pertanyaan: "Di rapat kita, apakah kritik yang beralasan disambut sebagai masukan, atau justru dihindari dan dianggap serangan?",
    praktik: "Sisihkan waktu di setiap rapat untuk masukan dan kritik, dengan satu aturan: setiap kritik disertai alasan dan usulan. Catat masukan yang diterima beserta tindak lanjutnya.",
    program: ["08"],
  },
  {
    nomor: 33,
    teks: "Dokumen dan sejarah organisasi belum dikelola dengan kuat.",
    kelompok: "evaluasi-arsip",
    pertanyaan: "Jika pengurus baru ingin tahu keputusan penting periode lalu, di mana mereka bisa menemukannya hari ini?",
    praktik: "Buat satu folder arsip bersama dengan struktur sederhana: notulensi, keputusan, laporan, dan dokumentasi. Pindahkan dokumen yang tersebar di ponsel pengurus ke sana.",
    program: ["10"],
  },
  {
    nomor: 34,
    teks: "Nama baik dan kekuatan batin HMI memudar.",
    kelompok: "tata-kelola",
    pertanyaan: "Bagaimana mahasiswa di kampus kita memandang HMI, dan pernahkah kita menanyakannya langsung?",
    praktik: "Tanyakan kepada sepuluh mahasiswa bukan anggota tiga kata yang terlintas saat mendengar HMI. Bahas jawabannya bersama pengurus tanpa membela diri, lalu pilih satu hal yang bisa diperbaiki.",
    program: ["06"],
  },
  {
    nomor: 35,
    teks: "Peran, jumlah, dan mutu HMI dinilai mengecil.",
    kelompok: "target-program",
    pertanyaan: "Dengan data apa kita menilai HMI membesar atau mengecil di kampus kita, atau selama ini hanya berdasarkan kesan?",
    praktik: "Susun tiga angka dasar komisariat: jumlah anggota aktif, peserta LK 1 tahun ini, dan karya kader. Perbarui setiap semester agar penilaian berangkat dari catatan, bukan kesan.",
    program: ["03", "04"],
  },
  {
    nomor: 36,
    teks: "HMI tidak memiliki media representatif sebagai penghubung dan ruang gagasan.",
    kelompok: "data-jaringan",
    pertanyaan: "Apakah kanal media komisariat kita lebih banyak memuat gagasan dan karya kader, atau hanya pengumuman dan ucapan?",
    praktik: "Tetapkan satu rubrik rutin di kanal media komisariat untuk tulisan atau karya kader. Terbitkan minimal dua karya dalam sebulan dan catat tanggapan pembacanya.",
    program: ["09"],
  },
  {
    nomor: 37,
    teks: "Jaringan organisasi HMI lemah.",
    kelompok: "data-jaringan",
    pertanyaan: "Apakah kita punya daftar alumni dan mitra yang bisa dihubungi, lengkap dengan bidang keahlian dan kesediaan mereka membantu?",
    praktik: "Mulai daftar jejaring sederhana berisi alumni dan mitra: bidang, kota, dan bentuk dukungan yang bersedia diberikan. Minta izin sebelum mencatat data mereka dan batasi siapa yang dapat mengaksesnya.",
    program: ["02", "12"],
  },
  {
    nomor: 38,
    teks: "HMI lambat mengikuti perkembangan sosial budaya yang sangat cepat.",
    kelompok: "pengetahuan",
    pertanyaan: "Perubahan apa di kampus dan ruang digital yang paling memengaruhi mahasiswa hari ini, dan sudahkah kita membahasnya?",
    praktik: "Minta kader angkatan termuda memaparkan perubahan yang mereka alami di kampus dan ruang digital dalam satu forum. Jadikan paparan itu bahan menyusun tema kajian berikutnya.",
    program: ["06", "08"],
  },
  {
    nomor: 39,
    teks: "Perbuatan buruk sebagian kader atau alumni merusak citra seluruh HMI.",
    kelompok: "tata-kelola",
    pertanyaan: "Apakah kita punya kode etik yang dipahami kader dan mekanisme yang adil ketika terjadi pelanggaran?",
    praktik: "Baca ulang ketentuan konstitusi tentang etika dan sanksi bersama pengurus. Tuliskan alur penanganan pelanggaran yang adil, termasuk hak untuk didengar, lalu kenalkan kepada kader baru.",
    program: ["11"],
  },
  {
    nomor: 40,
    teks: "Gejala politik uang dalam pemilihan ketua umum merusak moral kepemimpinan dan citra HMI.",
    kelompok: "tata-kelola",
    pertanyaan: "Apakah aturan pemilihan di forum kita, termasuk soal pembiayaan dan kampanye, tertulis jelas dan diketahui semua peserta?",
    praktik: "Tinjau tata tertib pemilihan yang berlaku bersama pengurus. Pastikan ketentuan tentang pembiayaan dan kampanye tertulis jelas, lalu catat usulan perbaikannya untuk forum berikutnya.",
    program: ["11"],
  },
  {
    nomor: 41,
    teks: "Disiplin organisasi anggota dan aktivis rendah.",
    kelompok: "tata-kelola",
    pertanyaan: "Apakah kesepakatan sederhana, seperti waktu rapat dan tenggat tugas, benar-benar dijalankan dan diperiksa bersama?",
    praktik: "Sepakati tiga aturan kerja pengurus, misalnya hadir tepat waktu, mengabari jika berhalangan, dan menyelesaikan tugas sesuai tenggat. Catat pelaksanaannya dan tinjau bersama di akhir bulan.",
    program: ["11"],
  },
  {
    nomor: 42,
    teks: "Aktivis terlalu berpikir umum dan global tanpa kedalaman yang memadai.",
    kelompok: "pengetahuan",
    pertanyaan: "Ketika membahas isu besar, apakah kita membawa data, bacaan, dan contoh lokal, atau hanya opini umum?",
    praktik: "Sepakati aturan diskusi bulan ini: setiap pembicara membawa minimal satu sumber atau data. Pilih satu isu nasional dan kaji dampaknya secara khusus di kampus atau daerah kita.",
    program: ["08"],
  },
  {
    nomor: 43,
    teks: "Keberhasilan masa lalu tidak dipelihara, ditingkatkan, dan dikonsolidasikan sebagai modal perjuangan.",
    kelompok: "evaluasi-arsip",
    pertanyaan: "Apa tiga keberhasilan komisariat kita dalam lima tahun terakhir, dan apakah caranya tercatat sehingga bisa diulang?",
    praktik: "Wawancarai dua mantan ketua komisariat tentang program yang paling berhasil di masanya. Tuliskan apa yang dilakukan, siapa yang terlibat, dan pelajarannya, lalu simpan di arsip.",
    program: ["10"],
  },
  {
    nomor: 44,
    teks: "HMI menghadapi risiko kehilangan jati diri dan kepribadian yang utuh.",
    kelompok: "tata-kelola",
    pertanyaan: "Apakah nilai dasar dan tujuan HMI benar-benar menjadi pertimbangan saat kita memilih program dan mengambil keputusan?",
    praktik: "Dalam rapat program berikutnya, ajukan satu pertanyaan untuk setiap usulan: bagaimana program ini membina kualitas Insan Cita? Catat jawabannya bersama keputusan.",
    program: ["10"],
  },
];
